### ISSUE TITLE
Konfiguration

### ISSUE THREAD

**Issue by Goersch** [soef/ioBroker.miele#5]
Hallo,
kann ich die IP eines Geräts irgendwo manuell einstellen? Broadcast funktioniert bei mir nicht, weil WLAN und iobroker in unterschiedlichen IP Adressbereichen sind.
Danke!
Georg

**Comment by soef** [comment]
Hallo, du kannst in der Root vom Adapter einen Datenpunkt anlegen in dem ein Array von IPs enthalten sein kann.  Also z.B.: setState ('miele.0.IPs', '[192.168.x.x]'). Ich weiß aber nicht ob die Pakete vom Gateway dann empfangen werden, wenn die beiden sich in unterschiedlichen Netzen befinden. Das Gateway sendet auch nur eine udp multicast/broadcast an 239.255.68.139:2810. Du kannst es ja einmal versuchen. 

Grüße!

**Comment by Goersch** [comment]
mh, in den Objekten gibt es kein "miele.0" (Adapter läuft) - entsprechend gibt es eine Fehlermeldung beim setState

**Comment by soef** [comment]
Hallo, hast du das aus einem JavaScript versucht? Dann musst du zuvor 
createState(''miele.0.IPs', '[192.168.x.x]'). In der Object-View des ioBroker.admins werden nur Adapter angezeigt, die auch Datenpunkte enthalten. Da der Miele Adapter noch keine IP empfangen hat, gibt e noch keine Datenpunkte. Auch den Datenpunkt IPs nicht. Versuche es einmal mit den createState...

**Comment by Goersch** [comment]
OK, den State hab ich angelegt - sonst passiert leider weiter nix.

2 Auffälligkeiten:
1) nach dem "createState" taucht dieser nicht im Object-Tree auf. Ich hätte ein Folder "miele.0" mit einem Eintrag "IPs" erwartet. Ein log(getState... ergibt die zu erwartenden Ausgabe. Der State ist also grundsätzlich angelegt.

2) allerdings finde ich im Object-Tree "system.adapter.miele.0" vom Typ "instance". Das sieht für mich merkwürdig aus, da die anderen Instanzen/Adapter sowas nicht anlegen/haben.

![georg](https://cloud.githubusercontent.com/assets/24088528/24330875/98192646-1228-11e7-8176-d99db3cd2e44.PNG)

**Comment by Goersch** [comment]
Schade, wird nicht gehen : die Broadcast Packages an 239.255.68.139 krieg ich nicht durch die firewall geroutet. Muss ich was am Netzwerk ändern.

**Comment by soef** [comment]
Hallo, komisch. Normalerweise werden in der Object-View alle Instanze-Objecte angezeigt, die auch Datenpunkte, Geräte oder Channels haben. Hast du oben in der Object-View einmal den Refresh-Button betätigt?

Aber wenn die Pakete an 239.255.68.139 sowieso von der Firewall nicht weitergegeben werden, bringt das wie anfangs schon geschrieben nichts.

Ich hoffe du bekommst Roten der Packete zwischen den beiden Netzen hin.

Grüße.
